// <auto-generated />
using System;
using FinTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinTrack.Migrations
{
    [DbContext(typeof(FinTrackDbContext))]
    [Migration("20260805220811_AddPluggyFaturaPagamento")]
    partial class AddPluggyFaturaPagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinTrack.Models.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Banco", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhMovimentacaoInterna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Tipo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataFinalEstimada")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("IdBanco")
                        .HasColumnType("int");

                    b.Property<int?>("IdRecorrente")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("Pagando")
                        .HasColumnType("bit");

                    b.Property<int?>("QntParcelas")
                        .HasColumnType("int");

                    b.Property<int>("QntParcelasPagas")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxaJuro")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ValorParcela")
                        .HasColumnType("money");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("money");

                    b.Property<decimal?>("ValorVista")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdBanco");

                    b.HasIndex("IdRecorrente");

                    b.HasIndex("IdUser");

                    b.ToTable("Divida", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.MetaInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<DateTime?>("DataAlvo")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoScope")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal>("ValorAlvo")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("MetaInvestimento", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Operador", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUser", "IdCategoria")
                        .IsUnique();

                    b.ToTable("Orcamento", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.PluggyConexao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientIdProtegido")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ClientSecretProtegido")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("PluggyConexao", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.PluggyFatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContaNome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContaPluggyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataUltimoPagamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<decimal?>("ValorMinimo")
                        .HasColumnType("money");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("money");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.HasIndex("IdUser");

                    b.ToTable("PluggyFatura", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.PluggyFaturaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContaPluggyId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdUser", "ContaPluggyId", "Data", "Valor")
                        .IsUnique();

                    b.ToTable("PluggyFaturaPagamento", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.PluggyInvestimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataVencimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Emissor")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("InvestmentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Isin")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("LucroInformado")
                        .HasColumnType("money");

                    b.Property<string>("MoedaCodigo")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeConector")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Quantidade")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("money");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Subtipo")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal?>("Taxa")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<decimal?>("TaxaAnualFixa")
                        .HasPrecision(9, 4)
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoTaxa")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("ValorCota")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("ValorDisponivelResgate")
                        .HasColumnType("money");

                    b.Property<decimal?>("ValorOriginal")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("InvestmentId")
                        .IsUnique();

                    b.ToTable("PluggyInvestimento", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.PluggyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconeUrl")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeConector")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UltimaSincronizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("PluggyItem", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Recorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("TipoVencimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Valor")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUser");

                    b.ToTable("Recorrente", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.SessaoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FimEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("InicioEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(36)
                        .IsUnicode(false)
                        .HasColumnType("varchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("SessaoUsuario", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContaNome")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContaPluggyId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContaTipo")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("data");

                    b.Property<string>("Desc")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("MerchantCnpj")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MerchantNome")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MoedaOriginalCodigo")
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("PluggyBillId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PluggyCategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PluggyCategoriaId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("PluggyDataCompra")
                        .HasColumnType("datetime2");

                    b.Property<string>("PluggyFaturaPrevista")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<int?>("PluggyParcelaAtual")
                        .HasColumnType("int");

                    b.Property<int?>("PluggyParcelaTotal")
                        .HasColumnType("int");

                    b.Property<string>("PluggyTransactionId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("PluggyValorCompraTotal")
                        .HasColumnType("money");

                    b.Property<decimal>("Valor")
                        .HasColumnType("money")
                        .HasColumnName("valor");

                    b.Property<decimal?>("ValorMoedaOriginal")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUser");

                    b.HasIndex("PluggyTransactionId")
                        .IsUnique()
                        .HasFilter("[PluggyTransactionId] IS NOT NULL");

                    b.ToTable("Transacao", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Categoria", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Categorias")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK_Categoria_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Divida", b =>
                {
                    b.HasOne("FinTrack.Models.Banco", "IdBancoNavigation")
                        .WithMany("Dividas")
                        .HasForeignKey("IdBanco")
                        .HasConstraintName("FK_Divida_Banco");

                    b.HasOne("FinTrack.Models.Recorrente", "IdRecorrenteNavigation")
                        .WithMany("Dividas")
                        .HasForeignKey("IdRecorrente")
                        .HasConstraintName("FK_Divida_Recorrente");

                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Dividas")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Divida_Usuario");

                    b.Navigation("IdBancoNavigation");

                    b.Navigation("IdRecorrenteNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.MetaInvestimento", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Metas")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MetaInvestimento_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Orcamento", b =>
                {
                    b.HasOne("FinTrack.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Orcamentos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Orcamento_Categoria");

                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Orcamentos")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Orcamento_Usuario");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.PluggyConexao", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithOne("PluggyConexao")
                        .HasForeignKey("FinTrack.Models.PluggyConexao", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PluggyConexao_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.PluggyFatura", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("PluggyFaturas")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PluggyFatura_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.PluggyFaturaPagamento", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("PluggyFaturaPagamentos")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PluggyFaturaPagamento_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.PluggyInvestimento", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("PluggyInvestimentos")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PluggyInvestimento_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.PluggyItem", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("PluggyItems")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PluggyItem_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Recorrente", b =>
                {
                    b.HasOne("FinTrack.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Recorrentes")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Recorrente_Categoria");

                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Recorrentes")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Recorrente_Usuario");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.SessaoUsuario", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Sessoes")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SessaoUsuario_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Transacao", b =>
                {
                    b.HasOne("FinTrack.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Transacao_Categoria");

                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Transacao_Usuario");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Banco", b =>
                {
                    b.Navigation("Dividas");
                });

            modelBuilder.Entity("FinTrack.Models.Categoria", b =>
                {
                    b.Navigation("Orcamentos");

                    b.Navigation("Recorrentes");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinTrack.Models.Recorrente", b =>
                {
                    b.Navigation("Dividas");
                });

            modelBuilder.Entity("FinTrack.Models.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Dividas");

                    b.Navigation("Metas");

                    b.Navigation("Orcamentos");

                    b.Navigation("PluggyConexao");

                    b.Navigation("PluggyFaturaPagamentos");

                    b.Navigation("PluggyFaturas");

                    b.Navigation("PluggyInvestimentos");

                    b.Navigation("PluggyItems");

                    b.Navigation("Recorrentes");

                    b.Navigation("Sessoes");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
