// <auto-generated />
using System;
using FinTrack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinTrack.Migrations
{
    [DbContext(typeof(FinTrackDbContext))]
    [Migration("20260729030811_AddCategoriaMovimentacaoFatura")]
    partial class AddCategoriaMovimentacaoFatura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinTrack.Models.Banco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Banco", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhMovimentacaoInterna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Tipo")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("Categoria", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Divida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataFinal")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataFinalEstimada")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("IdBanco")
                        .HasColumnType("int");

                    b.Property<int?>("IdRecorrente")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<bool>("Pagando")
                        .HasColumnType("bit");

                    b.Property<int?>("QntParcelas")
                        .HasColumnType("int");

                    b.Property<int>("QntParcelasPagas")
                        .HasColumnType("int");

                    b.Property<decimal?>("TaxaJuro")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal?>("ValorParcela")
                        .HasColumnType("money");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("money");

                    b.Property<decimal?>("ValorVista")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdBanco");

                    b.HasIndex("IdRecorrente");

                    b.HasIndex("IdUser");

                    b.ToTable("Divida", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.PluggyConexao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("ClientIdProtegido")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("ClientSecretProtegido")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUser")
                        .IsUnique();

                    b.ToTable("PluggyConexao", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.PluggyItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NomeConector")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UltimaSincronizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("PluggyItem", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Recorrente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<int>("TipoVencimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("Valor")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUser");

                    b.ToTable("Recorrente", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("data");

                    b.Property<string>("Desc")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("PluggyCategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PluggyCategoriaId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PluggyTransactionId")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("money")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUser");

                    b.HasIndex("PluggyTransactionId")
                        .IsUnique()
                        .HasFilter("[PluggyTransactionId] IS NOT NULL");

                    b.ToTable("Transacao", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("FinTrack.Models.Categoria", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Categorias")
                        .HasForeignKey("IdUser")
                        .HasConstraintName("FK_Categoria_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Divida", b =>
                {
                    b.HasOne("FinTrack.Models.Banco", "IdBancoNavigation")
                        .WithMany("Dividas")
                        .HasForeignKey("IdBanco")
                        .HasConstraintName("FK_Divida_Banco");

                    b.HasOne("FinTrack.Models.Recorrente", "IdRecorrenteNavigation")
                        .WithMany("Dividas")
                        .HasForeignKey("IdRecorrente")
                        .HasConstraintName("FK_Divida_Recorrente");

                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Dividas")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Divida_Usuario");

                    b.Navigation("IdBancoNavigation");

                    b.Navigation("IdRecorrenteNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.PluggyConexao", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithOne("PluggyConexao")
                        .HasForeignKey("FinTrack.Models.PluggyConexao", "IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PluggyConexao_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.PluggyItem", b =>
                {
                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("PluggyItems")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PluggyItem_Usuario");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Recorrente", b =>
                {
                    b.HasOne("FinTrack.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Recorrentes")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Recorrente_Categoria");

                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Recorrentes")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Recorrente_Usuario");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Transacao", b =>
                {
                    b.HasOne("FinTrack.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Transacao_Categoria");

                    b.HasOne("FinTrack.Models.Usuario", "IdUserNavigation")
                        .WithMany("Transacoes")
                        .HasForeignKey("IdUser")
                        .IsRequired()
                        .HasConstraintName("FK_Transacao_Usuario");

                    b.Navigation("IdCategoriaNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("FinTrack.Models.Banco", b =>
                {
                    b.Navigation("Dividas");
                });

            modelBuilder.Entity("FinTrack.Models.Categoria", b =>
                {
                    b.Navigation("Recorrentes");

                    b.Navigation("Transacoes");
                });

            modelBuilder.Entity("FinTrack.Models.Recorrente", b =>
                {
                    b.Navigation("Dividas");
                });

            modelBuilder.Entity("FinTrack.Models.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Dividas");

                    b.Navigation("PluggyConexao");

                    b.Navigation("PluggyItems");

                    b.Navigation("Recorrentes");

                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
